unique_name: Product Dim
object_type: dimension
label: Product Dim
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    filter_empty: 'yes'
    folder: Product Attributes
    levels:
      - unique_name: Product Category
      - unique_name: Product Class
      - unique_name: Product Brand
      - unique_name: Product Dimension
        secondary_attributes:
          - unique_name: d_i_color
            label: Product Color
            dataset: item
            folder: Product Attributes
            key_columns:
              - I_COLOR
            name_column: I_COLOR
            sort_column: I_COLOR
          - unique_name: d_i_size
            label: Product Size
            dataset: item
            folder: Product Attributes
            key_columns:
              - I_SIZE
            name_column: I_SIZE
            sort_column: I_SIZE
level_attributes:
  - unique_name: Product Category
    label: Product Category
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Siblings
    dataset: item
    key_columns:
      - I_CATEGORY_ID
    name_column: I_CATEGORY
    sort_column: empty_value
  - unique_name: Product Brand
    label: Product Brand
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Siblings
    dataset: item
    key_columns:
      - I_BRAND_ID
      - I_CLASS_ID
      - I_CATEGORY_ID
    name_column: I_BRAND
  - unique_name: Product Class
    label: Product Class
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Siblings
    dataset: item
    key_columns:
      - I_CLASS_ID
      - I_CATEGORY_ID
    name_column: I_CLASS
  - unique_name: Product Dimension
    label: Product Item
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Siblings
    dataset: item
    is_unique_key: true
    key_columns:
      - I_ITEM_SK
    name_column: I_PRODUCT_NAME
    sort_column: empty_value
type: standard
